Kuma-Boo/project-reignition

- Project/area/1 sand oasis/data/script/SandScorpion.cs
Fixes the flying eye attack's tracking.
> Fix Sand Scorpion flying eye

- Project/interface/gameplay/results/LevelResult.cs
Fixes a missing character when playing with a russian pc.
> Fix technical bonus

- Project/object/player/resource/script/CharacterController.cs
- Project/object/stage/common/resource/script/GrindRail.cs
> Fix grindstep bonus

- Project/area/1 sand oasis/act 1/map/MainAct.tscn
- Project/area/1 sand oasis/object/pillar/CircularPillar.tscn
- Project/area/1 sand oasis/object/pillar/SquarePillarMid.tscn
- Project/area/1 sand oasis/object/pillar/SquarePillarShort.tscn
- Project/area/1 sand oasis/object/pillar/SquarePillarTall.tscn
- Project/area/6 skeleton dome/act 1/camera/AutomationCam.tres
- Project/area/6 skeleton dome/act 1/camera/CavernBCam.tres
- Project/area/6 skeleton dome/act 1/camera/CavernCam.tres
- Project/area/6 skeleton dome/act 1/camera/CavernExitCam.tres
- Project/area/6 skeleton dome/act 1/camera/CavernPanelCam.tres
- Project/area/6 skeleton dome/act 1/camera/FieldBrawlCam.tres
- Project/area/6 skeleton dome/act 1/camera/FieldUpperPathCam.tres
- Project/area/6 skeleton dome/act 1/camera/HallCam.tres
- Project/area/6 skeleton dome/act 1/camera/SidleCam.tres
- Project/area/6 skeleton dome/act 1/camera/SpiralCam.tres
- Project/area/6 skeleton dome/act 1/camera/SpiralEndCam.tres
- Project/area/6 skeleton dome/act 1/map/MainAct.tscn
- Project/area/6 skeleton dome/object/platform/PlatformCavernFalling.tscn
- Project/object/trigger/modules/PlatformTrigger.cs
- Project/project.godot
Improves the accuracy of falling platforms and closes #92
I'm not sure if #78 is fixed or not. More testing is probably needed.
> Pillar fixes

- Project/interface/menu/options/Options.tscn
- Project/interface/menu/options/script/Options.cs
Fix options scroll not resetting
> Fix options scroll reset

- Project/.gitignore
- Project/Sonic Remake Project.csproj
- Project/interface/transition/TransitionManager.cs
> Load time fix

- Project/interface/gameplay/hud/HeadsUpDisplay.tscn
- Project/interface/gameplay/hud/script/HeadsUpDisplay.cs
- Project/interface/gameplay/results/LevelResult.cs
- Project/object/stage/StageSettings.cs
Adds a rank previewer, similar to Sonic Origins plus.
> Implement Rank Previewer

- Project/object/enemy/majin/Majin.tscn
- Project/object/enemy/majin/data/Majin.cs
Fixes Majins not despawning when launch is enabled, and "Snappy" travel transitions.
> Various Majin Fixes

- Project/object/enemy/Enemy.cs
- Project/object/enemy/flower/FlowerMajin.tscn
- Project/object/enemy/flower/data/FlowerMajin.cs
- Project/object/enemy/golem/data/GolemMajin.cs
- Project/object/enemy/majin/Majin.tscn
- Project/object/enemy/majin/data/Majin.cs
- Project/object/enemy/majin/data/sand oasis/BlueMajin.tscn
- Project/object/enemy/skeleton/data/SkeletonMajin.cs
- Project/object/player/resource/script/CharacterController.cs
- Project/object/trigger/modules/EventTrigger.cs
Closes #158 
Closes #78 
Also improves duplicating enemies in the inspector.
> Sand Oasis Fixes

- Project/area/2 dino jungle/act 1/Static.tscn
- Project/area/2 dino jungle/act 1/map/RaceAct.tscn
Fixes some dash panels and jump triggers
> Fix Race Act

- Project/core/Core.tscn
- Project/core/DebugManager.cs
- Project/core/Runtime.cs
- Project/object/player/Camera.tscn
- Project/object/player/resource/script/CameraController.cs
Fixes various issues with the free cam mode.
> Promo rewrite

- Project/area/2 dino jungle/act 1/camera/CaveRightEndCam.tres
- Project/area/2 dino jungle/act 1/camera/CaveRightSpringCam.tres
- Project/area/2 dino jungle/act 1/camera/CaveRightStartCam.tres
- Project/area/2 dino jungle/act 1/camera/JumpChainCarpetCam.tres
- Project/area/2 dino jungle/act 1/camera/JumpChainFollowCam.tres
- Project/area/2 dino jungle/act 1/camera/RiverBoatCam.tres
- Project/area/2 dino jungle/act 2/map/RingAct.tscn
- Project/object/player/resource/component/lockon/Lockon.tscn
- Project/object/player/resource/script/CharacterLockon.cs
- Project/resource/level data/dinosaur jungle/Act1Perfect.tres
- Project/resource/level data/dinosaur jungle/Act3Ring.tres
Also increases homing attack range.
> Clean Up Ring Act

- Project/area/1 sand oasis/act 3/map/RampageAct.tscn
- Project/area/1 sand oasis/act 3/map/RingAct.tscn
Restores the goal objects in SOAct3.
> SOAct3 Goal Restoration

- Project/interface/gameplay/hud/HeadsUpDisplay.tscn
- Project/interface/gameplay/hud/script/HeadsUpDisplay.cs
- Project/object/stage/pickups/resource/script/FireSoul.cs
Adds an alert when the player gets a fire soul.
> Add Fire Soul Alert

- Project/interface/gameplay/results/LevelResults.tscn
- Project/interface/gameplay/results/script/ExperienceResult.cs
- Project/interface/gameplay/results/script/LevelResult.cs
- Project/interface/menu/notification/NotificationMenu.cs
- Project/object/player/CharacterSpawn.tscn
- Project/object/stage/StageSettings.cs
Speed up transitions and fix exp not saving.
> Level completion fix

- Project/interface/menu/skill select/SkillOption.tscn
- Project/interface/menu/skill select/SkillSelect.tscn
- Project/interface/menu/skill select/script/SkillOption.cs
- Project/interface/menu/skill select/script/SkillSelect.cs
- Project/resource/script/SkillRing.cs
Reworks the skill menu to be more intuitive with drop downs instead of submenus.
> Skill select revamp

- Project/interface/menu/Menu.tscn
- Project/interface/menu/level select/LevelOption.tscn
- Project/interface/menu/level select/LevelSelect.tscn
- Project/interface/menu/level select/ReadyMenu.tscn
- Project/interface/menu/level select/WorldSelect.tscn
- Project/interface/menu/level select/script/LevelSelect.cs
- Project/interface/menu/main/MainMenu.tscn
- Project/interface/menu/save select/SaveSelect.tscn
- Project/interface/menu/skill select/SkillSelect.tscn
- Project/interface/menu/skill select/script/SkillSelect.cs
- Project/interface/menu/title/Title.tscn
- Project/resource/level data/dinosaur jungle/Act1Ring.tres
- Project/resource/level data/sand oasis/Act1Pearless.tres
- Project/resource/level data/skeleton dome/Act2Deathless.tres
- Project/resource/script/SkillRing.cs
- Revert skills to base skills when unequipping them.
- Adjusts the speed of various menus.
> Menu adjustments

- Project/interface/gameplay/results/script/ExperienceResult.cs
- Project/object/player/resource/script/CharacterAnimator.cs
- Project/object/stage/StageSettings.cs
Fixes various last minute bugs.
> SAGE Last Minute Patch

- Project/interface/font/bitmap fonts/Skill Select.fnt
- Project/interface/gameplay/pause/PauseMenu.tscn
Fixes some text issues with the pause menu.
> Text adjustments

- Project/area/1 sand oasis/data/script/SandScorpion.cs
- Project/core/DebugManager.cs
- Project/interface/gameplay/hud/HeadsUpDisplay.tscn
- Project/interface/gameplay/hud/script/HeadsUpDisplay.cs
- Project/interface/gameplay/results/LevelResults.tscn
- Project/interface/menu/NavigationButton.cs
- Project/interface/menu/level select/LevelSelect.tscn
- Project/interface/menu/level select/ReadyMenu.tscn
- Project/interface/menu/level select/WorldSelect.tscn
- Project/interface/menu/main/MainMenu.tscn
- Project/interface/menu/notification/NotificationMenu.tscn
- Project/interface/menu/options/Options.tscn
- Project/interface/menu/save select/SaveSelect.tscn
- Project/interface/menu/skill select/SkillSelect.tscn
- Project/locale/Locale.csv
- Project/object/player/resource/script/PlayerSkillController.cs
- Project/object/player/resource/script/old code/CharacterSkillManager.cs
- Project/object/player/resource/script/states/CatapultState.cs
- Project/object/player/resource/script/states/FlyingPotState.cs
- Project/object/player/resource/script/states/GrindState.cs
- Project/object/player/resource/script/states/GrindStepState.cs
- Project/object/player/resource/script/states/LaunchRingState.cs
- Project/object/player/resource/script/states/SidleState.cs
- Project/object/stage/genie/Uhu.cs
- Project/object/stage/pickups/resource/script/FireSoul.cs
Adds button prompts for various stage objects in the game.
> Action Prompts

- Project/object/player/CharacterSpawn.tscn
- Project/object/player/resource/component/SonicRoot.tscn
- Project/object/player/resource/script/PlayerController.cs
- Project/object/player/resource/script/states/GrindState.cs
- Project/object/player/resource/script/states/KnockbackState.cs
- Project/object/player/resource/script/states/SidleState.cs
- Project/object/trigger/state trigger/script/SidleTrigger.cs
> State Fixes

- Project/interface/transition/TransitionManager.cs
- Project/object/enemy/Enemy.cs
- Project/object/player/resource/script/PlayerController.cs
- Project/object/player/resource/script/PlayerStateMachine.cs
- Project/object/player/resource/script/states/BounceState.cs
- Project/object/player/resource/script/states/HomingAttackState.cs
- Project/object/stage/common/ItemBox.tscn
- Project/object/stage/pickups/resource/script/ItemBox.cs
Fixes premature input processing when starting a level.
Fixes bounce snapping.
Fixes softlock caused by a typo in #249 .
> Player Jank Fixes

- Project/interface/gameplay/pause/PauseMenu.cs
- Project/interface/transition/TransitionManager.cs
Refactors the pause menu to align better with the current style guides.
Fixes a softlock when pausing and respawning on the same frame.
Fixes pause binding conflict with Toggle Fullscreen.
> Fix Pausing

- Project/object/player/resource/script/camera/PlayerCameraController.cs
- Project/object/trigger/modules/CameraTrigger.cs
Adds Camera Blending based on distance.
An alternative implementation of #254 that plays nice with the dev branch.
> Feature: Camera blending

- Project/area/3 evil foundry/object/Fan.tscn
- Project/area/3 evil foundry/object/FanBroken.tscn
Adds missing visual effects to the spinning fans in Evil Foundry.
> Add Fan Flames

- Project/interface/menu/Description.cs
- Project/interface/menu/level select/script/WorldSelect.cs
- Project/interface/menu/main/MainMenu.cs
- Project/interface/menu/main/MainMenu.tscn
Fix a regression where the main menu's description wasn't updating its text properly.
> Fix/Menu Description

- Project/object/player/resource/component/Camera.tscn
- Project/object/stage/genie/Uhu.cs
Adds RubberBanding to Uhu for closer races.
> Uhu Rubberbanding

- Project/.gitignore
- Project/.vscode/launch.json
- Project/.vscode/tasks.json
Adds launch and task configs for debugging in VSCode.
> Improve Debugging in VSCode
